<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommunesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('communes')->delete();

        DB::table('communes')->insert(array (
            0 => array (
                'id' => 1,
                'district_id' => 225,
                'name' => 'Châu Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            1 => array (
                'id' => 2,
                'district_id' => 225,
                'name' => 'Hai Bà Trưng',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            2 => array (
                'id' => 3,
                'district_id' => 225,
                'name' => 'Lam Hạ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            3 => array (
                'id' => 4,
                'district_id' => 225,
                'name' => 'Lê Hồng Phong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            4 => array (
                'id' => 5,
                'district_id' => 225,
                'name' => 'Liêm Chính',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            5 => array (
                'id' => 6,
                'district_id' => 225,
                'name' => 'Lương Khánh Thiện',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            6 => array (
                'id' => 7,
                'district_id' => 225,
                'name' => 'Minh Khai',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            7 => array (
                'id' => 8,
                'district_id' => 225,
                'name' => 'Quang Trung',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            8 => array (
                'id' => 9,
                'district_id' => 225,
                'name' => 'Thanh Châu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            9 => array (
                'id' => 10,
                'district_id' => 225,
                'name' => 'Thanh Tuyền',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            10 => array (
                'id' => 11,
                'district_id' => 225,
                'name' => 'Trần Hưng Đạo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            11 => array (
                'id' => 12,
                'district_id' => 225,
                'name' => 'Đinh Xá',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            12 => array (
                'id' => 13,
                'district_id' => 225,
                'name' => 'Kim Bình',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            13 => array (
                'id' => 14,
                'district_id' => 225,
                'name' => 'Liêm Chung',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            14 => array (
                'id' => 15,
                'district_id' => 225,
                'name' => 'Liêm Tiết',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            15 => array (
                'id' => 16,
                'district_id' => 225,
                'name' => 'Liêm Tuyền',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            16 => array (
                'id' => 17,
                'district_id' => 225,
                'name' => 'Phù Vân',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            17 => array (
                'id' => 18,
                'district_id' => 225,
                'name' => 'Tiên Hải',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            18 => array (
                'id' => 19,
                'district_id' => 225,
                'name' => 'Tiên Hiệp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            19 => array (
                'id' => 20,
                'district_id' => 225,
                'name' => 'Tiên Tân',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            20 => array (
                'id' => 21,
                'district_id' => 225,
                'name' => 'Trịnh Xá',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            21 => array (
                'id' => 22,
                'district_id' => 226,
                'name' => 'Vĩnh Trụ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            22 => array (
                'id' => 23,
                'district_id' => 226,
                'name' => 'Bắc Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            23 => array (
                'id' => 24,
                'district_id' => 226,
                'name' => 'Chân Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            24 => array (
                'id' => 25,
                'district_id' => 226,
                'name' => 'Chính Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            25 => array (
                'id' => 26,
                'district_id' => 226,
                'name' => 'Công Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            26 => array (
                'id' => 27,
                'district_id' => 226,
                'name' => 'Đạo Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            27 => array (
                'id' => 28,
                'district_id' => 226,
                'name' => 'Đức Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            28 => array (
                'id' => 29,
                'district_id' => 226,
                'name' => 'Hòa Hậu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            29 => array (
                'id' => 30,
                'district_id' => 226,
                'name' => 'Hợp Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            30 => array (
                'id' => 31,
                'district_id' => 226,
                'name' => 'Nguyên Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            31 => array (
                'id' => 32,
                'district_id' => 226,
                'name' => 'Nhân Bình',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            32 => array (
                'id' => 33,
                'district_id' => 226,
                'name' => 'Nhân Khang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            33=> array (
                'id' => 34,
                'district_id' => 226,
                'name' => 'Nhân Mỹ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            34 => array (
                'id' => 35,
                'district_id' => 226,
                'name' => 'Nhân Nghĩa',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            35 => array (
                'id' => 36,
                'district_id' => 226,
                'name' => 'Nhân Thịnh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            36 => array (
                'id' => 37,
                'district_id' => 226,
                'name' => 'Phú Phúc',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            37 => array (
                'id' => 38,
                'district_id' => 226,
                'name' => 'Tiến Thắng',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            38 => array (
                'id' => 39,
                'district_id' => 226,
                'name' => 'Trần Hưng Đạo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            39 => array (
                'id' => 40,
                'district_id' => 226,
                'name' => 'Văn Lý',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            40 => array (
                'id' => 41,
                'district_id' => 226,
                'name' => 'Xuân Khê',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            41 => array (
                'id' => 42,
                'district_id' => 227,
                'name' => 'Bạch Thượng',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            42 => array (
                'id' => 43,
                'district_id' => 227,
                'name' => 'Châu Giang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            43 => array (
                'id' => 44,
                'district_id' => 227,
                'name' => 'Duy Hải',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            44 => array (
                'id' => 45,
                'district_id' => 227,
                'name' => 'Duy Minh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            45 => array (
                'id' => 46,
                'district_id' => 227,
                'name' => 'Đồng Văn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            46 => array (
                'id' => 47,
                'district_id' => 227,
                'name' => 'Hòa Mạc',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            47 => array (
                'id' => 48,
                'district_id' => 227,
                'name' => 'Hoàng Đông',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            48 => array (
                'id' => 49,
                'district_id' => 227,
                'name' => 'Tiên Nội',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            49 => array (
                'id' => 50,
                'district_id' => 227,
                'name' => 'Yên Bắc',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            50 => array (
                'id' => 51,
                'district_id' => 227,
                'name' => 'Chuyên Ngoại',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            51 => array (
                'id' => 52,
                'district_id' => 227,
                'name' => 'Mộc Bắc',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            52 => array (
                'id' => 53,
                'district_id' => 227,
                'name' => 'Mộc Nam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            53 => array (
                'id' => 54,
                'district_id' => 227,
                'name' => 'Tiên Ngoại',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            54 => array (
                'id' => 55,
                'district_id' => 227,
                'name' => 'Tiên Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            55 => array (
                'id' => 56,
                'district_id' => 227,
                'name' => 'Trác Văn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            56 => array (
                'id' => 57,
                'district_id' => 227,
                'name' => 'Yên Nam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            57 => array (
                'id' => 58,
                'district_id' => 228,
                'name' => 'Bình Mỹ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            58 => array (
                'id' => 59,
                'district_id' => 228,
                'name' => 'An Đổ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            59 => array (
                'id' => 60,
                'district_id' => 228,
                'name' => 'An Lão',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            60 => array (
                'id' => 61,
                'district_id' => 228,
                'name' => 'An Ninh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            61 => array (
                'id' => 62,
                'district_id' => 228,
                'name' => 'An Nội',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            62 => array (
                'id' => 63,
                'district_id' => 228,
                'name' => 'Bình Nghĩa',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            63 => array (
                'id' => 64,
                'district_id' => 228,
                'name' => 'Bồ Đề',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            64 => array (
                'id' => 65,
                'district_id' => 228,
                'name' => 'Bối Cầu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            65 => array (
                'id' => 66,
                'district_id' => 228,
                'name' => 'Đồn Xá',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            66 => array (
                'id' => 67,
                'district_id' => 228,
                'name' => 'Đồng Du',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            67 => array (
                'id' => 68,
                'district_id' => 228,
                'name' => 'Hưng Công',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            68 => array (
                'id' => 69,
                'district_id' => 228,
                'name' => 'La Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            69 => array (
                'id' => 70,
                'district_id' => 228,
                'name' => 'Ngọc Lũ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            70 => array (
                'id' => 71,
                'district_id' => 228,
                'name' => 'Tiêu Động',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            71 => array (
                'id' => 72,
                'district_id' => 228,
                'name' => 'Tràng An',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            72 => array (
                'id' => 73,
                'district_id' => 228,
                'name' => 'Trung Lương',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            73 => array (
                'id' => 74,
                'district_id' => 228,
                'name' => 'Vũ Bản',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            74 => array (
                'id' => 75,
                'district_id' => 229,
                'name' => 'Quế',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            75 => array (
                'id' => 76,
                'district_id' => 229,
                'name' => 'Ba Sao',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            76 => array (
                'id' => 77,
                'district_id' => 229,
                'name' => 'Đại Cương',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            77 => array (
                'id' => 78,
                'district_id' => 229,
                'name' => 'Đồng Hóa',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            78 => array (
                'id' => 79,
                'district_id' => 229,
                'name' => 'Hoàng Tây',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            79 => array (
                'id' => 80,
                'district_id' => 229,
                'name' => 'Khả Phong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            80 => array (
                'id' => 81,
                'district_id' => 229,
                'name' => 'Lê Hồ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            81 => array (
                'id' => 82,
                'district_id' => 229,
                'name' => 'Liên Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            82 => array (
                'id' => 83,
                'district_id' => 229,
                'name' => 'Ngọc Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            83 => array (
                'id' => 84,
                'district_id' => 229,
                'name' => 'Nguyễn Úy',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            84 => array (
                'id' => 85,
                'district_id' => 229,
                'name' => 'Nhật Tân',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            85 => array (
                'id' => 86,
                'district_id' => 229,
                'name' => 'Nhật Tựu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            86 => array (
                'id' => 87,
                'district_id' => 229,
                'name' => 'Tân Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            87 => array (
                'id' => 88,
                'district_id' => 229,
                'name' => 'Thanh Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            88 => array (
                'id' => 89,
                'district_id' => 229,
                'name' => 'Thụy Lôi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            89 => array (
                'id' => 90,
                'district_id' => 229,
                'name' => 'Tượng Lĩnh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            90 => array (
                'id' => 91,
                'district_id' => 229,
                'name' => 'Văn Xá',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            91 => array (
                'id' => 92,
                'district_id' => 230,
                'name' => 'Tân Thanh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            92 => array (
                'id' => 93,
                'district_id' => 230,
                'name' => 'Kiện Khê',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            93 => array (
                'id' => 94,
                'district_id' => 230,
                'name' => 'Liêm Cần',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            94 => array (
                'id' => 95,
                'district_id' => 230,
                'name' => 'Liêm Phong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            95 => array (
                'id' => 96,
                'district_id' => 230,
                'name' => 'Liêm Sơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            96 => array (
                'id' => 97,
                'district_id' => 230,
                'name' => 'Liêm Thuận',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            97 => array (
                'id' => 98,
                'district_id' => 230,
                'name' => 'Liêm Túc',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            98 => array (
                'id' => 99,
                'district_id' => 230,
                'name' => 'Thanh Hà',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            99 => array (
                'id' => 100,
                'district_id' => 230,
                'name' => 'Thanh Hải',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            100 => array (
                'id' => 101,
                'district_id' => 230,
                'name' => 'Thanh Hương',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            101 => array (
                'id' => 102,
                'district_id' => 230,
                'name' => 'Thanh Nghị',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            102 => array (
                'id' => 103,
                'district_id' => 230,
                'name' => 'Thanh Nguyên',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            103 => array (
                'id' => 104,
                'district_id' => 230,
                'name' => 'Thanh Phong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            104 => array (
                'id' => 105,
                'district_id' => 230,
                'name' => 'Thanh Tâm',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            105 => array (
                'id' => 106,
                'district_id' => 230,
                'name' => 'Thanh Tân',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            106 => array (
                'id' => 107,
                'district_id' => 230,
                'name' => 'Thanh Thủy',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ));
    }
}
