<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('employees')->delete();

        DB::table('employees')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'code' => '312',
                    'name' => 'Tạ Văn Toại',
                    'img_path' => 'dist/employee_img/toaitv.jpeg',
                    'private_email' => null,
                    'company_email' => 'tavantoai@honghafeed.com.vn',
                    'phone' => '0999999999',
                    'relative_phone' => '0999999999',
                    'date_of_birth' => '1984-01-01',
                    'cccd' => '0999999999',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an thành phố Hà Nội',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2014-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '2612200828',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            1 =>
                array (
                    'id' => 2,
                    'code' => '912',
                    'name' => 'Nguyễn Văn Cường',
                    'img_path' => 'dist/employee_img/cuongnv.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenvancuong@honghafeed.com.vn',
                    'phone' => '0999999998',
                    'relative_phone' => '0999999998',
                    'date_of_birth' => '1988-05-05',
                    'cccd' => '0999999998',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an tỉnh Hải Dương',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2016-09-12',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '112102013',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            2 =>
                array (
                    'id' => 3,
                    'code' => '1992',
                    'name' => 'Phạm Hồng Hải',
                    'img_path' => 'dist/employee_img/haiph.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamhonghai@honghafeed.com.vn',
                    'phone' => '0999999997',
                    'relative_phone' => '0999999997',
                    'date_of_birth' => '1988-01-01',
                    'cccd' => '0999999997',
                    'issued_date' => '1988-01-01',
                    'issued_by' => 'công an tỉnh Thái Nguyên',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 2,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2020-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '131215666',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            3 =>
                array (
                    'id' => 4,
                    'code' => '2142',
                    'name' => 'Bùi Thị Nụ',
                    'img_path' => 'dist/employee_img/nubt.jpeg',
                    'private_email' => null,
                    'company_email' => 'buithinu@honghafeed.com.vn',
                    'phone' => '0999999996',
                    'relative_phone' => '0999999996',
                    'date_of_birth' => '1989-01-01',
                    'cccd' => '0999999996',
                    'issued_date' => '1989-01-01',
                    'issued_by' => 'công an tỉnh Nam Định',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2021-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '112219452',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            4 =>
                array (
                    'id' => 5,
                    'code' => '2272',
                    'name' => 'Trần Xuân Trường',
                    'img_path' => 'dist/employee_img/truongtx.jpeg',
                    'private_email' => null,
                    'company_email' => 'tranxuantruong@honghafeed.com.vn',
                    'phone' => '0999999995',
                    'relative_phone' => '0999999995',
                    'date_of_birth' => '1998-01-01',
                    'cccd' => '0999999995',
                    'issued_date' => '1998-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 4,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '3 năm',
                    'join_date' => '2022-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3520732284',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            5 =>
                array (
                    'id' => 6,
                    'code' => '468',
                    'name' => 'Phạm Thành Thứ',
                    'img_path' => 'dist/employee_img/thupt.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamthanhthu@honghafeed.com.vn',
                    'phone' => '0999999994',
                    'relative_phone' => '0999999994',
                    'date_of_birth' => '1983-01-01',
                    'cccd' => '0999999994',
                    'issued_date' => '1983-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 5,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3508001831',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            6 =>
                array (
                    'id' => 7,
                    'code' => '353',
                    'name' => 'Ngô Tiến Trung',
                    'img_path' => 'dist/employee_img/trungnt.jpeg',
                    'private_email' => null,
                    'company_email' => 'ngotientrung@honghafeed.com.vn',
                    'phone' => '0999999993',
                    'relative_phone' => '0999999993',
                    'date_of_birth' => '1987-01-01',
                    'cccd' => '0999999993',
                    'issued_date' => '1987-01-01',
                    'issued_by' => 'công an tỉnh Nam Định',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 5,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2012-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '5611003199',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            7 =>
                array (
                    'id' => 8,
                    'code' => '2261',
                    'name' => 'Dương Văn Thắng',
                    'img_path' => 'dist/employee_img/thangnv.jpeg',
                    'private_email' => null,
                    'company_email' => 'duongvanthang@honghafeed.com.vn',
                    'phone' => '0999999992',
                    'relative_phone' => '0999999992',
                    'date_of_birth' => '1996-01-01',
                    'cccd' => '0999999992',
                    'issued_date' => '1987-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '3 năm',
                    'join_date' => '2023-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3521072963',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            8 =>
                array (
                    'id' => 9,
                    'code' => '226',
                    'name' => 'Cao Xuân Thuyên',
                    'img_path' => 'dist/employee_img/thuyencx.jpeg',
                    'private_email' => null,
                    'company_email' => 'caoxuanthuyen@honghafeed.com.vn',
                    'phone' => '0999999991',
                    'relative_phone' => '0999999991',
                    'date_of_birth' => '1986-01-01',
                    'cccd' => '0999999991',
                    'issued_date' => '1986-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '13 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3509005222',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            9 =>
                array (
                    'id' => 10,
                    'code' => '240',
                    'name' => 'Phạm Xuân Giáp',
                    'img_path' => 'dist/employee_img/giappx.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamxuangiap@honghafeed.com.vn',
                    'phone' => '0999999990',
                    'relative_phone' => '0999999990',
                    'date_of_birth' => '1985-01-01',
                    'cccd' => '0999999990',
                    'issued_date' => '1985-01-01',
                    'issued_by' => 'công an tỉnh Thái Bình',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3513021895',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            10 =>
                array (
                    'id' => 11,
                    'code' => '241',
                    'name' => 'Hoàng Thị Thu',
                    'img_path' => 'dist/employee_img/thuypt.jpeg',
                    'private_email' => null,
                    'company_email' => 'hoangthithu@honghafeed.com.vn',
                    'phone' => '0999999989',
                    'relative_phone' => '0999999989',
                    'date_of_birth' => '1985-01-01',
                    'cccd' => '0999999989',
                    'issued_date' => '2021-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 7,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Độc thân',
                    'bhxh' => '110138331',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            11 =>
                array (
                    'id' => 12,
                    'code' => '275',
                    'name' => 'Đinh Thị Ngà',
                    'img_path' => 'dist/employee_img/ngadt.jpeg',
                    'private_email' => null,
                    'company_email' => 'dinhthinga@honghafeed.com.vn',
                    'phone' => '0999999988',
                    'relative_phone' => '0999999988',
                    'date_of_birth' => '1984-01-01',
                    'cccd' => '0999999988',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 8,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '9108010562',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            12 =>
                array (
                    'id' => 13,
                    'code' => '248',
                    'name' => 'Trần Thị Thu Hương',
                    'img_path' => 'dist/employee_img/huongttt.jpeg',
                    'private_email' => null,
                    'company_email' => 'tranthithuhuong@honghafeed.com.vn',
                    'phone' => '0999999987',
                    'relative_phone' => '0999999987',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999987',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 8,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3513027228',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            13 =>
                array (
                    'id' => 14,
                    'code' => '252',
                    'name' => 'Nguyễn Thị Thiết',
                    'img_path' => 'dist/employee_img/thietnt.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenthithiet@honghafeed.com.vn',
                    'phone' => '0999999986',
                    'relative_phone' => '0999999986',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999986',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3514021636',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            14 =>
                array (
                    'id' => 15,
                    'code' => '554',
                    'name' => 'Cao Thị Phượng',
                    'img_path' => 'dist/employee_img/phuongct.jpeg',
                    'private_email' => null,
                    'company_email' => 'caothiphuong@honghafeed.com.vn',
                    'phone' => '0999999985',
                    'relative_phone' => '0999999985',
                    'date_of_birth' => '1991-01-01',
                    'cccd' => '0999999985',
                    'issued_date' => '1991-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 4,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2013-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3516020356',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            15 =>
                array (
                    'id' => 16,
                    'code' => '868',
                    'name' => 'Đỗ Thị Thu Hương',
                    'img_path' => 'dist/employee_img/huongdtt.jpeg',
                    'private_email' => null,
                    'company_email' => 'dothithuhuong@honghafeed.com.vn',
                    'phone' => '0999999984',
                    'relative_phone' => '0999999984',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999984',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2016-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3513010693',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            16 =>
                array (
                    'id' => 17,
                    'code' => '557',
                    'name' => 'Nguyễn Thị Thúy Nga',
                    'img_path' => 'dist/employee_img/ngantt.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenthithuynga@honghafeed.com.vn',
                    'phone' => '0999999983',
                    'relative_phone' => '0999999983',
                    'date_of_birth' => '1993-01-01',
                    'cccd' => '0999999983',
                    'issued_date' => '1993-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 7,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3512021656',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            17 =>
                array (
                    'id' => 18,
                    'code' => '001',
                    'name' => 'Đỗ Đức Tiến',
                    'img_path' => 'dist/employee_img/tiendd.jpeg',
                    'private_email' => null,
                    'company_email' => 'doductien@honghafeed.com.vn',
                    'phone' => '0999999982',
                    'relative_phone' => '0999999982',
                    'date_of_birth' => '1967-01-01',
                    'cccd' => '0999999982',
                    'issued_date' => '1967-01-01',
                    'issued_by' => 'công an thành phố Hà Nội',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '30 năm',
                    'join_date' => '2003-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => 0102036663,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            18 =>
                array (
                    'id' => 19,
                    'code' => '598',
                    'name' => 'Lê Thị Hồng',
                    'img_path' => 'dist/employee_img/honglt.jpeg',
                    'private_email' => null,
                    'company_email' => 'lethihong@honghafeed.com.vn',
                    'phone' => '0999999981',
                    'relative_phone' => '0999999981',
                    'date_of_birth' => '1992-01-01',
                    'cccd' => '0999999981',
                    'issued_date' => '1992-01-01',
                    'issued_by' => 'công an tỉnh Thanh Hóa',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 5,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => 114032841,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            19 =>
                array (
                    'id' => 20,
                    'code' => '1821',
                    'name' => 'Triệu Thị Hương',
                    'img_path' => 'dist/employee_img/huongtt.jpeg',
                    'private_email' => null,
                    'company_email' => 'trieuthihuong@honghafeed.com.vn',
                    'phone' => '0999999980',
                    'relative_phone' => '0999999980',
                    'date_of_birth' => '1988-01-01',
                    'cccd' => '0999999980',
                    'issued_date' => '1988-01-01',
                    'issued_by' => 'công an tỉnh Nam Định',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2021-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '0130298441',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            20 =>
                array (
                    'id' => 21,
                    'code' => '1631',
                    'name' => 'Nguyễn Văn Long',
                    'img_path' => 'dist/employee_img/longnv.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenvanlong@honghafeed.com.vn',
                    'phone' => '0999999979',
                    'relative_phone' => '0999999979',
                    'date_of_birth' => '1982-01-01',
                    'cccd' => '0999999979',
                    'issued_date' => '1982-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 8,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2018-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '9104015192',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            21 =>
                array (
                    'id' => 22,
                    'code' => '090',
                    'name' => 'Lưu Văn Tuấn',
                    'img_path' => 'dist/employee_img/tuanlv.jpeg',
                    'private_email' => null,
                    'company_email' => 'luuvantuan@honghafeed.com.vn',
                    'phone' => '0999999978',
                    'relative_phone' => '0999999978',
                    'date_of_birth' => '1985-01-01',
                    'cccd' => '0999999978',
                    'issued_date' => '1985-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 2,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2004-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '2708007803',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            22 =>
                array (
                    'id' => 23,
                    'code' => '326',
                    'name' => 'Lê Văn Khoa',
                    'img_path' => 'dist/employee_img/khoalv.jpeg',
                    'private_email' => null,
                    'company_email' => 'levankhoa@honghafeed.com.vn',
                    'phone' => '0999999977',
                    'relative_phone' => '0999999977',
                    'date_of_birth' => '1989-01-01',
                    'cccd' => '0999999977',
                    'issued_date' => '1989-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3513023320',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            23 =>
                array (
                    'id' => 24,
                    'code' => '594',
                    'name' => 'Phạm Thị Thơm',
                    'img_path' => 'dist/employee_img/thompt.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamthithom@honghafeed.com.vn',
                    'phone' => '0999999976',
                    'relative_phone' => '0999999976',
                    'date_of_birth' => '1993-01-01',
                    'cccd' => '0999999976',
                    'issued_date' => '1993-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2016-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3516021804',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            24 =>
                array (
                    'id' => 25,
                    'code' => '481',
                    'name' => 'Trần Thị Bích Phương',
                    'img_path' => 'dist/employee_img/phuongttb.jpeg',
                    'private_email' => null,
                    'company_email' => 'tranthibichphuong@honghafeed.com.vn',
                    'phone' => '0999999975',
                    'relative_phone' => '0999999975',
                    'date_of_birth' => '1989-01-01',
                    'cccd' => '0999999975',
                    'issued_date' => '1989-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3514040220',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            25 =>
                array (
                    'id' => 26,
                    'code' => '444',
                    'name' => 'Lê Thị Hà',
                    'img_path' => 'dist/employee_img/halt.jpeg',
                    'private_email' => null,
                    'company_email' => null,
                    'phone' => '0999999974',
                    'relative_phone' => '0999999974',
                    'date_of_birth' => '1968-01-01',
                    'cccd' => '0999999974',
                    'issued_date' => '1968-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2013-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3509000848',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            26 =>
                array (
                    'id' => 27,
                    'code' => '170',
                    'name' => 'Dương Thị Hằng',
                    'img_path' => 'dist/employee_img/hangdt.jpeg',
                    'private_email' => null,
                    'company_email' => 'duongthihang@honghafeed.com.vn',
                    'phone' => '0999999973',
                    'relative_phone' => '0999999973',
                    'date_of_birth' => '1989-06-03',
                    'cccd' => '0999999973',
                    'issued_date' => '2024-01-09',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2021-01-01',
                    'marriage_status' => 'Kết hôn',
                    'bhxh' => '3509000847',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
        ));
    }
}
