<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('positions')->delete();

        DB::table('positions')->insert(array (
            0 => array (
                    'id' => 1,
                    'name' => 'Trưởng phòng Kiểm Soát',
                    'department_id' => 2,
                    'division_id' => null,
                    'insurance_salary' => 6000000,
                    'position_salary' => 15000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/truong_phong_kiem_soat.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            1 => array (
                    'id' => 2,
                    'name' => 'Trưởng nhóm Kiểm Soát',
                    'department_id' => 2,
                    'division_id' => 2,
                    'insurance_salary' => 4500000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/truong_nhom_kiem_soat.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            2 => array (
                    'id' => 3,
                    'name' => 'Nhân viên Kiểm Soát',
                    'department_id' => 2,
                    'division_id' => 2,
                    'insurance_salary' => 4500000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 5000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_kiem_soat.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            3 => array (
                    'id' => 4,
                    'name' => 'Chuyên viên IT',
                    'department_id' => 2,
                    'division_id' => 1,
                    'insurance_salary' => 4500000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cv_it.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            4 => array (
                    'id' => 5,
                    'name' => 'Nhân viên IT',
                    'department_id' => 2,
                    'division_id' => 1,
                    'insurance_salary' => 4500000,
                    'position_salary' => 7000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_it.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            5 => array (
                    'id' => 6,
                    'name' => 'Giám đốc Hành Chính',
                    'department_id' => 3,
                    'division_id' => 3,
                    'insurance_salary' => 9000000,
                    'position_salary' => 10000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gd_hc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            6 => array (
                    'id' => 7,
                    'name' => 'Nhân viên Hành Chính',
                    'department_id' => 3,
                    'division_id' => 3,
                    'insurance_salary' => 4500000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_hc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            7 => array (
                    'id' => 8,
                    'name' => 'Trưởng nhóm Nhân Sự',
                    'department_id' => 3,
                    'division_id' => 4,
                    'insurance_salary' => 6000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 15000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tn_nhan_su.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            8 => array (
                    'id' => 9,
                    'name' => 'Nhân viên Nhân Sự',
                    'department_id' => 3,
                    'division_id' => 4,
                    'insurance_salary' => 6000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_nhan_su.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            9 => array (
                    'id' => 10,
                    'name' => 'Nhân viên Nhà Bếp',
                    'department_id' => 3,
                    'division_id' => 5,
                    'insurance_salary' => 4500000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 5000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_nha_bep.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            10 => array (
                    'id' => 11,
                    'name' => 'Nhân viên Tạp Vụ',
                    'department_id' => 3,
                    'division_id' => 6,
                    'insurance_salary' => 4500000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 5000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_tap_vu.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            11 => array (
                    'id' => 12,
                    'name' => 'Nhân viên Trồng Rau',
                    'department_id' => 3,
                    'division_id' => 7,
                    'insurance_salary' => 4500000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 5000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_trong_rau.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            12 => array (
                    'id' => 13,
                    'name' => 'Nhân viên Lái Xe',
                    'department_id' => 3,
                    'division_id' => 8,
                    'insurance_salary' => 5000000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_lai_xe.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            13 => array (
                    'id' => 14,
                    'name' => 'Trưởng ban Tài Chính',
                    'department_id' => 4,
                    'division_id' => 9,
                    'insurance_salary' => 10000000,
                    'position_salary' => 15000000,
                    'max_capacity_salary' => 20000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tb_tai_chinh.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            14 => array (
                    'id' => 15,
                    'name' => 'Phó ban Tài Chính',
                    'department_id' => 4,
                    'division_id' => 9,
                    'insurance_salary' => 10000000,
                    'position_salary' => 15000000,
                    'max_capacity_salary' => 18000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/pb_tai_chinh.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            15 => array (
                    'id' => 16,
                    'name' => 'Nhân viên cân',
                    'department_id' => 4,
                    'division_id' => 10,
                    'insurance_salary' => 4500000,
                    'position_salary' => 5000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_can.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            16 => array (
                    'id' => 17,
                    'name' => 'Nhân viên bán hàng',
                    'department_id' => 4,
                    'division_id' => 11,
                    'insurance_salary' => 4500000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_can.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            17 => array (
                    'id' => 18,
                    'name' => 'Nhân viên kế toán',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_ke_toan.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            18 => array (
                    'id' => 19,
                    'name' => 'Trưởng phòng kế toán',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 9000000,
                    'position_salary' => 15000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tp_ke_toan.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            19 => array (
                    'id' => 20,
                    'name' => 'Chuyên viên kế toán',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 8000000,
                    'position_salary' => 10000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cv_ke_toan.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            20 => array (
                    'id' => 21,
                    'name' => 'Trưởng nhóm Sale Admin',
                    'department_id' => 5,
                    'division_id' => 12,
                    'insurance_salary' => 8000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tn_admin.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            21 => array (
                    'id' => 22,
                    'name' => 'Nhân viên Sale Admin',
                    'department_id' => 5,
                    'division_id' => 12,
                    'insurance_salary' => 8000000,
                    'position_salary' => 5000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_admin.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            22 => array (
                    'id' => 23,
                    'name' => 'Giám đốc kỹ thuật thị trường',
                    'department_id' => 5,
                    'division_id' => 13,
                    'insurance_salary' => 15000000,
                    'position_salary' => 10000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gd_kttt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            23 => array (
                    'id' => 24,
                    'name' => 'Nhân viên kỹ thuật thị trường',
                    'department_id' => 5,
                    'division_id' => 13,
                    'insurance_salary' => 8000000,
                    'position_salary' => 5000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 2500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_kttt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            24 => array (
                    'id' => 25,
                    'name' => 'Giám đốc kỹ thuật trại',
                    'department_id' => 5,
                    'division_id' => 14,
                    'insurance_salary' => 15000000,
                    'position_salary' => 10000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gd_ktt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            25 => array (
                    'id' => 26,
                    'name' => 'Nhân viên kỹ thuật trại',
                    'department_id' => 5,
                    'division_id' => 14,
                    'insurance_salary' => 8000000,
                    'position_salary' => 5000000,
                    'max_capacity_salary' => 8000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_ktt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            26 => array (
                    'id' => 27,
                    'name' => 'Giám đốc kinh doanh GSGC',
                    'department_id' => 5,
                    'division_id' => 15,
                    'insurance_salary' => 10000000,
                    'position_salary' => 18000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gd_gsgc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            27 => array (
                    'id' => 28,
                    'name' => 'Phó giám đốc kinh doanh GSGC',
                    'department_id' => 5,
                    'division_id' => 15,
                    'insurance_salary' => 10000000,
                    'position_salary' => 15000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/pgd_gsgc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            28 => array (
                    'id' => 29,
                    'name' => 'Giám đốc miền GSGC',
                    'department_id' => 5,
                    'division_id' => 15,
                    'insurance_salary' => 10000000,
                    'position_salary' => 12000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdm_gsgc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            29 => array (
                    'id' => 30,
                    'name' => 'Giám sát BH GSGC',
                    'department_id' => 5,
                    'division_id' => 15,
                    'insurance_salary' => 10000000,
                    'position_salary' => 12000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gs_gsgc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            30 => array (
                    'id' => 31,
                    'name' => 'Nhân viên KD GSGC',
                    'department_id' => 5,
                    'division_id' => 15,
                    'insurance_salary' => 8000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 2500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_gsgc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            31 => array (
                    'id' => 32,
                    'name' => 'Nhân viên KD Thủy Sản',
                    'department_id' => 5,
                    'division_id' => 16,
                    'insurance_salary' => 8000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 2500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_ts.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            32 => array (
                    'id' => 33,
                    'name' => 'Giám đốc KD Thuốc',
                    'department_id' => 5,
                    'division_id' => 17,
                    'insurance_salary' => 18000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gd_tty.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            33 => array (
                    'id' => 34,
                    'name' => 'Phó giám đốc KD Thuốc',
                    'department_id' => 5,
                    'division_id' => 17,
                    'insurance_salary' => 15000000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 10000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/pgd_tty.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            34 => array (
                    'id' => 35,
                    'name' => 'Tổ trưởng tổ trộn mix',
                    'department_id' => 6,
                    'division_id' => 18,
                    'insurance_salary' => 5000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 2000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tt_premix.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            35 => array (
                    'id' => 36,
                    'name' => 'Nhân viên trộn mix',
                    'department_id' => 6,
                    'division_id' => 18,
                    'insurance_salary' => 5000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 1500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_premix.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            36 => array (
                    'id' => 37,
                    'name' => 'Tổ trưởng tổ bốc xếp',
                    'department_id' => 6,
                    'division_id' => 19,
                    'insurance_salary' => 8000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tt_bx.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            37 => array (
                    'id' => 38,
                    'name' => 'Nhân viên bốc xếp',
                    'department_id' => 6,
                    'division_id' => 19,
                    'insurance_salary' => 5000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_bx.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            38 => array (
                    'id' => 39,
                    'name' => 'Trưởng bộ phận Kho',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 10000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tp_kho.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            39 => array (
                    'id' => 40,
                    'name' => 'Trưởng Kho nguyên liệu',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 80000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tp_kho_nl.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            40 => array (
                    'id' => 41,
                    'name' => 'Trưởng Kho thành phẩm',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 80000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/tp_kho_tp.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            41 => array (
                    'id' => 42,
                    'name' => 'Thủ kho vi lượng',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 70000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/thu_kho_vl.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            42 => array (
                    'id' => 43,
                    'name' => 'Thủ kho bao bì',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 70000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/thu_kho_bb.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            43 => array (
                    'id' => 44,
                    'name' => 'Thủ kho thuốc',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 70000000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 9000000,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/thu_kho_tty.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
        ));
    }
}
