<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PositionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('positions')->delete();

        DB::table('positions')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'name' => 'Nhân viên lái xe',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 3000000,
                    'position_allowance' => 1000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_lai_xe.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            1 =>
                array (
                    'id' => 2,
                    'name' => 'Nhân viên nấu ăn',
                    'department_id' => 9,
                    'division_id' => 16,
                    'insurance_salary' => 4500000,
                    'position_salary' => 5000000,
                    'max_capacity_salary' => 2000000,
                    'position_allowance' => 1500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_nau_an.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            2 =>
                array (
                    'id' => 3,
                    'name' => 'Nhân viên bảo vệ',
                    'department_id' => 9,
                    'division_id' => 4,
                    'insurance_salary' => 4500000,
                    'position_salary' => 6000000,
                    'max_capacity_salary' => 4000000,
                    'position_allowance' => 2000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_bao_ve.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            3 =>
                array (
                    'id' => 4,
                    'name' => 'Công nhân kỹ thuật trại',
                    'department_id' => 8,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 4000000,
                    'max_capacity_salary' => 4000000,
                    'position_allowance' => 3000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cn_ktt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            4 =>
                array (
                    'id' => 5,
                    'name' => 'Nhân viên KTTT heo',
                    'department_id' => 8,
                    'division_id' => 6,
                    'insurance_salary' => 4500000,
                    'position_salary' => 7000000,
                    'max_capacity_salary' => 5000000,
                    'position_allowance' => 4000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_kttt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            5 =>
                array (
                    'id' => 6,
                    'name' => 'Nhân viên kinh doanh GSGC',
                    'department_id' => 8,
                    'division_id' => 7,
                    'insurance_salary' => 4500000,
                    'position_salary' => 8000000,
                    'max_capacity_salary' => 6000000,
                    'position_allowance' => 5000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_kd.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            6 =>
                array (
                    'id' => 7,
                    'name' => 'Nhân viên kỹ thuật trại KD',
                    'department_id' => 8,
                    'division_id' => 8,
                    'insurance_salary' => 4500000,
                    'position_salary' => 8500000,
                    'max_capacity_salary' => 5500000,
                    'position_allowance' => 45000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_ktt.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            7 =>
                array (
                    'id' => 8,
                    'name' => 'Nhân viên kinh doanh TS',
                    'department_id' => 8,
                    'division_id' => 9,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9000000,
                    'max_capacity_salary' => 7000000,
                    'position_allowance' => 7000000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_ts.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            8 =>
                array (
                    'id' => 9,
                    'name' => 'Nhân viên kinh doanh thuốc',
                    'department_id' => 8,
                    'division_id' => 10,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_tty.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            9 =>
                array (
                    'id' => 10,
                    'name' => 'Nhân viên Admin',
                    'department_id' => 3,
                    'division_id' => 3,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/nv_adm_tm.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            10 =>
                array (
                    'id' => 11,
                    'name' => 'Bác sĩ thú y',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/bsty.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            11 =>
                array (
                    'id' => 12,
                    'name' => 'Chuyên viên bảo trì cơ',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cv_btc.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            12 =>
                array (
                    'id' => 13,
                    'name' => 'Chuyên viên dinh dưỡng',
                    'department_id' => 15,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cv_dd.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            13 =>
                array (
                    'id' => 14,
                    'name' => 'Công nhân nghiền mẫu',
                    'department_id' => 11,
                    'division_id' => 5,
                    'insurance_salary' => 4500000,
                    'position_salary' => 9500000,
                    'max_capacity_salary' => 7500000,
                    'position_allowance' => 7500000,
                    'recruitment_standard_file' => 'dist/recruitment_standard/cn_nm.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            14 =>
                array (
                    'id' => 15,
                    'name' => 'Chủ tịch HĐQT',
                    'department_id' => 1,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/ct.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            15 =>
                array (
                    'id' => 16,
                    'name' => 'Phó ban bảo vệ',
                    'department_id' => 9,
                    'division_id' => 4,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/ct.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            16 =>
                array (
                    'id' => 17,
                    'name' => 'GĐ bảo trì',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            17 =>
                array (
                    'id' => 18,
                    'name' => 'GĐ hành chính',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            18 =>
                array (
                    'id' => 19,
                    'name' => 'GĐK kiểm soát',
                    'department_id' => 2,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            19 =>
                array (
                    'id' => 20,
                    'name' => 'GĐK quản lý chất lượng',
                    'department_id' => 11,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            20 =>
                array (
                    'id' => 21,
                    'name' => 'GĐ sản xuất',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            21 =>
                array (
                    'id' => 22,
                    'name' => 'GĐ vùng',
                    'department_id' => 8,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            22 =>
                array (
                    'id' => 23,
                    'name' => 'Giám sát bán hàng',
                    'department_id' => 8,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            23 =>
                array (
                    'id' => 24,
                    'name' => 'Giám sát bán hàng tập sự',
                    'department_id' => 8,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            24 =>
                array (
                    'id' => 25,
                    'name' => 'Nhân viên kế toán kho',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            25 =>
                array (
                    'id' => 26,
                    'name' => 'Nhân viên kế toán bán hàng',
                    'department_id' => 4,
                    'division_id' => 13,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            26 =>
                array (
                    'id' => 27,
                    'name' => 'Nhân viên kế toán tổng hợp',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            27 =>
                array (
                    'id' => 28,
                    'name' => 'Kiểm soát viên kế toán',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            28 =>
                array (
                    'id' => 29,
                    'name' => 'Nhân viên KTTT gia cầm',
                    'department_id' => 8,
                    'division_id' => 6,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            29 =>
                array (
                    'id' => 30,
                    'name' => 'Nhân viên KTTT thủy sản',
                    'department_id' => 8,
                    'division_id' => 6,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            30 =>
                array (
                    'id' => 31,
                    'name' => 'Nhân viên bảo trì',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            31 =>
                array (
                    'id' => 32,
                    'name' => 'Nhân viên bảo trì điện - tự động hóa',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            32 =>
                array (
                    'id' => 33,
                    'name' => 'Nhân viên bảo trì trại',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            33 =>
                array (
                    'id' => 34,
                    'name' => 'Nhân viên cân',
                    'department_id' => 4,
                    'division_id' => 14,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            34 =>
                array (
                    'id' => 35,
                    'name' => 'Nhân viên giám sát bán hàng',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            35 =>
                array (
                    'id' => 36,
                    'name' => 'Nhân viên giao nhận',
                    'department_id' => 3,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            36 =>
                array (
                    'id' => 37,
                    'name' => 'Nhân viên hành chính',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            37 =>
                array (
                    'id' => 38,
                    'name' => 'Nhân viên hành chính trại',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            38 =>
                array (
                    'id' => 39,
                    'name' => 'Nhân viên IT nhà máy',
                    'department_id' => 2,
                    'division_id' => 24,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            39 =>
                array (
                    'id' => 40,
                    'name' => 'Chuyên viên IT',
                    'department_id' => 2,
                    'division_id' => 24,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            40 =>
                array (
                    'id' => 41,
                    'name' => 'Nhân viên IT trại',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            // 41 =>
            //     array (
            //         'id' => 42,
            //         'name' => 'Nhân viên KCS nguyên liệu',
            //         'department_id' => 11,
            //         'division_id' => 17,
            //         'insurance_salary' => 4500000,
            //         'position_salary' => 0,
            //         'max_capacity_salary' => 0,
            //         'position_allowance' => 0,
            //         'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
            //         'created_at' => Carbon::now(),
            //         'updated_at' => Carbon::now(),
            //     ),
            42 =>
                array (
                    'id' => 43,
                    'name' => 'Nhân viên phân tích',
                    'department_id' => 11,
                    'division_id' => 5,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            43 =>
                array (
                    'id' => 44,
                    'name' => 'Nhân viên nhân sự',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            44 =>
                array (
                    'id' => 45,
                    'name' => 'Nhân viên pháp chế',
                    'department_id' => 14,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            45 =>
                array (
                    'id' => 46,
                    'name' => 'Nhân viên tạp vụ',
                    'department_id' => 9,
                    'division_id' => 15,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            46 =>
                array (
                    'id' => 47,
                    'name' => 'Nhân viên thống kê SX',
                    'department_id' => 6,
                    'division_id' => 11,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            47 =>
                array (
                    'id' => 48,
                    'name' => 'Nhân viên thủ kho bảo trì',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            48 =>
                array (
                    'id' => 49,
                    'name' => 'Nhân viên thủ kho thành phẩm',
                    'department_id' => 6,
                    'division_id' => 11,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            49 =>
                array (
                    'id' => 50,
                    'name' => 'Nhân viên trộn mix',
                    'department_id' => 7,
                    'division_id' => 17,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            50 =>
                array (
                    'id' => 51,
                    'name' => 'Nhân viên trồng rau',
                    'department_id' => 9,
                    'division_id' => 19,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            51 =>
                array (
                    'id' => 52,
                    'name' => 'Nhân viên vận hành lò hơi',
                    'department_id' => 6,
                    'division_id' => 12,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            52 =>
                array (
                    'id' => 53,
                    'name' => 'Nhân viên vận hành máy',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            53 =>
                array (
                    'id' => 54,
                    'name' => 'Nhân viên vận hành máy ép viên',
                    'department_id' => 6,
                    'division_id' => 11,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            54 =>
                array (
                    'id' => 55,
                    'name' => 'Nhân viên vận hành mixer',
                    'department_id' => 6,
                    'division_id' => 11,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            55 =>
                array (
                    'id' => 56,
                    'name' => 'Nhân viên vận hành silo, xá',
                    'department_id' => 6,
                    'division_id' => 17,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            56 =>
                array (
                    'id' => 57,
                    'name' => 'Nhân viên xuất nhập khẩu',
                    'department_id' => 3,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            57 =>
                array (
                    'id' => 58,
                    'name' => 'Phó giám đốc kinh doanh',
                    'department_id' => 8,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            58 =>
                array (
                    'id' => 59,
                    'name' => 'Phó phòng kỹ thuật',
                    'department_id' => 15,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            59 =>
                array (
                    'id' => 60,
                    'name' => 'Phó ban pháp chế',
                    'department_id' => 14,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            60 =>
                array (
                    'id' => 61,
                    'name' => 'Phó ban quản lý dự án',
                    'department_id' => 13,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            61 =>
                array (
                    'id' => 62,
                    'name' => 'Phó ban tài chính',
                    'department_id' => 4,
                    'division_id' => 23,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            62 =>
                array (
                    'id' => 63,
                    'name' => 'Nhân viên kiểm soát',
                    'department_id' => 2,
                    'division_id' => 25,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            63 =>
                array (
                    'id' => 64,
                    'name' => 'Quản lý trại',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            64 =>
                array (
                    'id' => 65,
                    'name' => 'Nhân viên kỹ thuật trại PT',
                    'department_id' => 12,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            65 =>
                array (
                    'id' => 66,
                    'name' => 'Nhân viên KCS nguyên liệu',
                    'department_id' => 11,
                    'division_id' => 20,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            66 =>
                array (
                    'id' => 67,
                    'name' => 'Nhân viên KCS TP TS',
                    'department_id' => 11,
                    'division_id' => 21,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ),
            67 =>
                array (
                    'id' => 68,
                    'name' => 'Nhân viên KCS TP GS',
                    'department_id' => 11,
                    'division_id' => 22,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            68 =>
                array (
                    'id' => 69,
                    'name' => 'Trưởng phòng kiểm soát',
                    'department_id' => 2,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            69 =>
                array (
                    'id' => 70,
                    'name' => 'Trưởng phòng hành chính nhân sự',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            70 =>
                array (
                    'id' => 71,
                    'name' => 'Trưởng phòng thu mua',
                    'department_id' => 3,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            71 =>
                array (
                    'id' => 72,
                    'name' => 'Trưởng phòng kế toán',
                    'department_id' => 4,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            72 =>
                array (
                    'id' => 73,
                    'name' => 'Trưởng phòng bảo trì',
                    'department_id' => 5,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            73 =>
                array (
                    'id' => 74,
                    'name' => 'Trưởng phòng sản xuất',
                    'department_id' => 6,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            74 =>
                array (
                    'id' => 75,
                    'name' => 'Trưởng bộ phận kho',
                    'department_id' => 7,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            75 =>
                array (
                    'id' => 76,
                    'name' => 'Trưởng phòng truyền thông',
                    'department_id' => 10,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            76 =>
                array (
                    'id' => 77,
                    'name' => 'Trưởng phòng kỹ thuật',
                    'department_id' => 15,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            77 =>
                array (
                    'id' => 78,
                    'name' => 'Trưởng nhóm kiểm soát',
                    'department_id' => 2,
                    'division_id' => 25,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            78 =>
                array (
                    'id' => 79,
                    'name' => 'Trưởng phòng chất lượng',
                    'department_id' => 11,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            79 =>
                array (
                    'id' => 80,
                    'name' => 'Tổ trưởng tổ KCS nguyên liệu',
                    'department_id' => 11,
                    'division_id' => 20,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            80 =>
                array (
                    'id' => 81,
                    'name' => 'Tổ trưởng tổ KCS thành phẩm',
                    'department_id' => 11,
                    'division_id' => 22,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            81 =>
                array (
                    'id' => 82,
                    'name' => 'Trưởng bộ phận SX thủy sản',
                    'department_id' => 6,
                    'division_id' => 12,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            // 82 =>
            //     array (
            //         'id' => 83,
            //         'name' => 'Phó phòng kỹ thuật',
            //         'department_id' => 15,
            //         'division_id' => null,
            //         'insurance_salary' => 4500000,
            //         'position_salary' => 0,
            //         'max_capacity_salary' => 0,
            //         'position_allowance' => 0,
            //         'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
            //         'created_at' => Carbon::now(),
            //         'updated_at' => Carbon::now(),
            //     ),
            83 =>
                array (
                    'id' => 84,
                    'name' => 'Trưởng bộ phận phân tích',
                    'department_id' => 11,
                    'division_id' => 5,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            84 =>
                array (
                    'id' => 85,
                    'name' => 'Phó phòng chất lượng',
                    'department_id' => 11,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            85 =>
                array (
                    'id' => 86,
                    'name' => 'Phó phòng hành chính nhân sự',
                    'department_id' => 9,
                    'division_id' => null,
                    'insurance_salary' => 4500000,
                    'position_salary' => 0,
                    'max_capacity_salary' => 0,
                    'position_allowance' => 0,
                    'recruitment_standard_file' => 'dist/recruitment_standard/gdkt_hn.pdf',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
        ));
    }
}
